server:
 port: 8081

spring:
 datasource:
   url: jdbc:mysql://localhost:3306/product_db
   username: root
   password: vish123@
   driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
   hibernate:
     database-platform: org.hibernate.dialect.MySQL57InnoDBDialect;
     ddl-auto: update
# application:
#   name: PRODUCT-SERVICE
#
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    regster-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_ADDRESS:http://localhost:8762/eureka}



